from pydantic import BaseModel, Field, ConfigDict
from typing import Literal, Optional

# Explicit Tool Allow-list constant
ALLOWED_ACTIONS = [
    "check_agent_calendar",
    "get_property_access_rules",
    "book_viewing",
    "suggest_alternative_time",
    "escalate_to_human_broker",
    "final_answer"
]

class ActionInput(BaseModel):
    """Explicit parameters schema for tool actions, ensuring strict JSON schema compliance."""
    model_config = ConfigDict(extra="forbid")
    property_id: Optional[str] = Field(default=None, description="Target property ID (e.g. APT-102 or APT-105)")
    agent_id: Optional[str] = Field(default=None, description="Target agent ID (e.g. AG-01 or AG-02)")
    customer_name: Optional[str] = Field(default=None, description="Customer name for booking")
    time_slot: Optional[str] = Field(default=None, description="Target time slot (e.g. Today 17:00, Today 20:00, Tomorrow 11:00)")
    reason: Optional[str] = Field(default=None, description="Escalation reason")
    response_text: Optional[str] = Field(default=None, description="Final response in Egyptian Arabic")

class AgentStep(BaseModel):
    """
    Strict Pydantic Schema for every step generated by the Constrained ReAct Agent.
    Un-allowed actions or malformed JSON inputs are rejected immediately during validation.
    """
    model_config = ConfigDict(extra="forbid")
    thought: str = Field(
        ...,
        description="Detailed step-by-step reasoning explaining what fact is needed next."
    )
    action: Literal[
        "check_agent_calendar",
        "get_property_access_rules",
        "book_viewing",
        "suggest_alternative_time",
        "escalate_to_human_broker",
        "final_answer"
    ] = Field(
        ...,
        description="The exact tool action to invoke. Must be one of the explicit allow-listed functions."
    )
    action_input: ActionInput = Field(
        default_factory=ActionInput,
        description="Key-value arguments matching the target tool function parameters."
    )
    is_final: bool = Field(
        default=False,
        description="Set to true if this step produces the final polite Arabic response to the user."
    )
